### ISSUE TITLE
Can't use string ("default_expires_in") as a HASH

### ISSUE THREAD

**Issue by bolav** [oalders/www-mechanize-cached#10]
Seems WWW::Mechanize::Cached is broken after a Cache::BaseCache upgrade. I get
Can't use string ("default_expires_in") as a HASH ref while "strict refs" in use at /Users/bolav/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Cache/BaseCache.pm line 430.
This solves it for me:
https://github.com/bolav/www-mechanize-cached/commit/a02130eace47b03576f6dfcaf5bdc2d300aea41d

**Comment by oalders** [comment]
Closed via #11

**Comment by oalders** [comment]
New release on its way to CPAN.
